ERP/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class BrandController : Controller
    {
        //
        // GET: /Brand/

        public ActionResult Index()
        {
            return View();
        } 

    }
}

ERP/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class DashboardController : Controller
    {
        //
        // GET: /Dashboard/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ERP/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {

            if (Session["sess_USER_NO"] == null)
            {
                Response.Redirect("~/login");

            }
            else
                return View(); 


            return View();
        }

    }
}

ERP/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace ERP.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        private ERPEntities db = new ERPEntities();

        public ActionResult Index()
        {

            if (Session["sess_USER_NO"] != null)
            {
                Response.Redirect("~/home");
               
            }
            else
            {
                return View();
            }
            return View();
            
        }

        [HttpPost]
        public ActionResult Index(SEC_USER sec_user)
        {
            SEC_USER_LOGIN_Result user = db.SEC_USER_LOGIN(sec_user.USER_NAME, sec_user.USER_PWD, 1).FirstOrDefault();
            //SEC_USER(sec_user.USER_NAME, sec_user.USER_PWD, null).FirstOrDefault();
            if (user != null && user.USER_NO > 0)
            {
                
                string sess_id = Session.SessionID;
                string ip_addr = Request.ServerVariables["REMOTE_ADDR"];
                // string device_id =    CustomValidator.GetDeviceId();


                SEC_USER_LOGONS_INSERT_Result LOGON_NO = db.SEC_USER_LOGONS_INSERT(user.USER_NO, ip_addr, null, null, null, null, sess_id, null, null).First();

                Session["sess_sec_users"] = user;
                Session["sess_USER_NO"] = user.USER_NO;
                Session["sess_USER_NAME"] = user.USER_NAME;
                Session["sess_LOGON_NO"] = LOGON_NO;

                Response.Redirect("~/home");

            }

            return View();
        }


        public ActionResult Logout()
        {

            Session.Abandon();
            Response.Redirect("~/login");
            return View();

        }


        public ActionResult Home()
        {
            decimal USER_NO = decimal.Parse(Session["sess_USER_NO"].ToString());

            //decimal? expense_approve_count = db.TRN_EXPENSE_APPROVAL_COUNT(USER_NO).FirstOrDefault();
            //ViewBag.expense_approve_count = expense_approve_count;


            return View();
        }

    }
}

ERP/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ERP.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult Index()
        {
            if (Session["sess_USER_NO"] == null)
            {
                Response.Redirect("~/login");

            }
            else
                return View(); 
            
            return View();
        }

        public ActionResult Add()
        {
            return View();
        }

    }
}

ERP/Views/Brand/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<a href="#" class="show-sidebar">
			<i class="fa fa-bars"></i>
		</a>
		<ol class="breadcrumb pull-left">
			<li><a href="/brand/">Brand</a></li>
			<li><a href="/brand/add">Add Brand</a></li>
		</ol>
		<div id="social" class="pull-right">
			<a href="#"><i class="fa fa-google-plus"></i></a>
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-youtube"></i></a>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12">
        @using (Html.BeginForm("Add", "Brand", FormMethod.Post, new { @id = "addBrandForm" }))
        { 
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i>
					<span>Add Brand Name form</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<h4 class="page-header">Add Brand Name form</h4>
				<form class="form-horizontal" role="form">
					<div class="form-group">
						<label class="col-sm-2 control-label">Brand Name</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" name="BOOK_BRAND_NAME" placeholder="BOOK BRAND NAME" data-toggle="tooltip" data-placement="bottom" title="Tooltip for name">
						</div>
						<label class="col-sm-2 control-label">Brand Name Bangla</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" name="BOOK_BRAND_NAME_B" placeholder="Brand Name Bangla" data-toggle="tooltip" data-placement="bottom" title="Tooltip for last name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Brand Code</label>
						<div class="col-sm-4">
							<input type="text" name="BOOK_BRAND_CODE" class="form-control" placeholder="Code">
						</div>
						
					</div>
					
			          <br />
						<div class="form-group">
						<label class="col-sm-2 control-label" for="form-styles">Brand Description</label>
						<div class="col-sm-10">
								<textarea class="form-control" rows="5" name="BOOK_BRAND_DESC" id="wysiwig_simple"></textarea>
						</div>
					</div>
					
					
					<div class="clearfix"></div>
					<div class="form-group">
						
						
						<div class="col-sm-2">
							<button type="button" onclick="sent_data('/Brand/add')" class="btn btn-primary btn-label-left">
							<span><i class="fa fa-clock-o"></i></span>
								Save
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
        }   
	</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        WinMove();
    });
</script>

ERP/Views/Brand/Edit.cshtml
@{
    ViewBag.Title = "Brand:Edit";
}

<h2>Edit</h2>

ERP/Views/Brand/Index.cshtml
@{
    ViewBag.Title = "Add";
   
}

<h2>Brand</h2>

ERP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index1";
    Layout = "~/Views/shared/_content.cshtml"; 
}




   
<section class="content-header">
<h1>
System Board
<small></small>
</h1>
<ol class="breadcrumb">
<li><a href="~/home/index"><i class="fa fa-dashboard"></i> Home</a></li>
<li class="active">Dashboard</li>
</ol>

</section>





<!-- Main content -->
<section class="content">

<h2>Index</h2>


</section><!-- /.Main content -->

ERP/Views/Login/Index.cshtml
<!DOCTYPE html>
<html class="bg-black">
    <head>
        <meta charset="UTF-8">
        <title>OG ERP | Log in</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css">
        

        <!-- font Awesome -->
 
        <link href="@Url.Content("~/Content/css/font-awesome.min.css")" rel="stylesheet" type="text/css">
        <!-- Ionicons -->
        
        <link href="@Url.Content("~/Content/css/ionicons.min.css")" rel="stylesheet" type="text/css">
       
       
        <!-- Theme style -->
        <link href="@Url.Content("~/Content/css/AdminLTE.css")" rel="stylesheet" type="text/css">

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    
        <![endif]-->
               <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- jQuery UI 1.10.3 -->
           <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>

        <!-- AdminLTE App -->
       
         <script src="@Url.Content("~/Scripts/AdminLTE/app.js")"></script>

    </head>
    <body class="bg-blue">
    
        <div class="form-box" id="login-box">
            <div class="header">Login</div>
           @using (Html.BeginForm("", "Login/Index", FormMethod.Post, new { @id = "loginForm" }))
     { 
                <div class="body bg-gray">
                    <div class="form-group">
                        <input type="text" name="USER_NAME" required class="form-control" placeholder="User ID"/>
                    </div>
                    <div class="form-group">
                        <input type="password" name="USER_PWD" required  class="form-control" placeholder="Password"/>
                    </div>          
                    <div class="form-group">
                        <input type="checkbox" name="remember_me"/> Remember me
                    </div>
                </div>
                <div class="footer">                                                               
                    <button type="submit" class="btn bg-olive btn-block">Log Me In</button>  
                    
                    <p><a href="#">I forgot my password</a></p>
                   
                </div>
           
               }
            <div class="margin text-center">
                <span>Omicon Group</span>
               


            </div>
        </div>

             <!-- jQuery 2.0.2 -->
      

    </body>
</html>

ERP/Views/User/Add.cshtml
@{
    ViewBag.Title = "Users Add";
    Layout = "~/Views/shared/_content.cshtml"; 
}

<h2>Create User</h2>

<div class="row">
	<div id="breadcrumb" class="col-xs-12">
		<a href="#" class="show-sidebar">
			<i class="fa fa-bars"></i>
		</a>
		<ol class="breadcrumb pull-left">
			<li><a href="/brand/">Brand</a></li>
			<li><a href="/brand/add">Add Brand</a></li>
		</ol>
		<div id="social" class="pull-right">
			<a href="#"><i class="fa fa-google-plus"></i></a>
			<a href="#"><i class="fa fa-facebook"></i></a>
			<a href="#"><i class="fa fa-twitter"></i></a>
			<a href="#"><i class="fa fa-linkedin"></i></a>
			<a href="#"><i class="fa fa-youtube"></i></a>
		</div>
	</div>
</div>

<div class="row">
	<div class="col-xs-12 col-sm-12">
        @using (Html.BeginForm("Add", "Brand", FormMethod.Post, new { @id = "addBrandForm" }))
        { 
		<div class="box">
			<div class="box-header">
				<div class="box-name">
					<i class="fa fa-search"></i>
					<span>Add Brand Name form</span>
				</div>
				<div class="box-icons">
					<a class="collapse-link">
						<i class="fa fa-chevron-up"></i>
					</a>
					<a class="expand-link">
						<i class="fa fa-expand"></i>
					</a>
					<a class="close-link">
						<i class="fa fa-times"></i>
					</a>
				</div>
				<div class="no-move"></div>
			</div>
			<div class="box-content">
				<h4 class="page-header">Add Brand Name form</h4>
				<form class="form-horizontal" role="form">
					<div class="form-group">
						<label class="col-sm-2 control-label">Brand Name</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" name="BOOK_BRAND_NAME" placeholder="BOOK BRAND NAME" data-toggle="tooltip" data-placement="bottom" title="Tooltip for name">
						</div>
						<label class="col-sm-2 control-label">Brand Name Bangla</label>
						<div class="col-sm-4">
							<input type="text" class="form-control" name="BOOK_BRAND_NAME_B" placeholder="Brand Name Bangla" data-toggle="tooltip" data-placement="bottom" title="Tooltip for last name">
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Brand Code</label>
						<div class="col-sm-4">
							<input type="text" name="BOOK_BRAND_CODE" class="form-control" placeholder="Code">
						</div>
						
					</div>
					
			          <br />
						<div class="form-group">
						<label class="col-sm-2 control-label" for="form-styles">Brand Description</label>
						<div class="col-sm-10">
								<textarea class="form-control" rows="5" name="BOOK_BRAND_DESC" id="wysiwig_simple"></textarea>
						</div>
					</div>
					
					
					<div class="clearfix"></div>
					<div class="form-group">
						
						
						<div class="col-sm-2">
							<button type="button" onclick="sent_data('/Brand/add')" class="btn btn-primary btn-label-left">
							<span><i class="fa fa-clock-o"></i></span>
								Save
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
        }   
	</div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        WinMove();
    });
</script>

ERP/Views/User/Edit.cshtml
@{
    ViewBag.Title = "Brand:Edit";
}

<h2>Edit</h2>

ERP/Views/User/Index.cshtml
<section class="content-header">
<h1>
User List
<small>User Panel</small>
</h1>
<ol class="breadcrumb">
<li><a href="~/home/index"><i class="fa fa-dashboard"></i> Home</a></li>
<li class="active">User Panel</li>
</ol>

</section>





<!-- Main content -->
<section class="content">

<h2>This is User List</h2>


</section><!-- /.Main content -->

ERP/Views/shared/_content.cshtml
@RenderPage("~/Views/shared/_head.cshtml")

@RenderPage("~/Views/shared/_header.cshtml")
<!--Start Container-->

<aside id="preLoader"><img border="0" src="http://192.168.1.1/device/images/loading_large.gif"></aside>
  <div class="wrapper row-offcanvas row-offcanvas-left">
              <!-- Left side column. contains the logo and sidebar -->
            <aside class="left-side sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
@RenderPage("~/Views/shared/_sidebar_left.cshtml")
            </aside>
            
            <!-- Right side column. Contains the navbar and content of the page -->
            
            <aside id="contentArea" class="right-side">

           
             
         
            @RenderBody()  
           
            
               
            </aside><!-- /.right-side -->

   </div>



@RenderPage("~/Views/shared/_footer.cshtml")

ERP/Views/shared/_footer.cshtml
 
    
</body>
</html>

ERP/Views/shared/_head.cshtml
<head>
 <meta charset="utf-8">
		<title>OG ERP</title>
		<meta name="description" content="description">
		<meta name="author" content="nazrul">
		<meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
        <!-- bootstrap 3.0.2 -->
        <link href="@Url.Content("~/Content/css/bootstrap.min.css")" rel="stylesheet" type="text/css">
        
        <!-- font Awesome -->
 
        <link href="@Url.Content("~/Content/css/font-awesome.min.css")" rel="stylesheet" type="text/css">
        <!-- Ionicons -->
        
        <link href="@Url.Content("~/Content/css/ionicons.min.css")" rel="stylesheet" type="text/css">
       
       
        <!-- Theme style -->
        <link href="@Url.Content("~/Content/css/AdminLTE.css")" rel="stylesheet" type="text/css">

             
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
        <!-- jQuery UI 1.10.3 -->
        <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script> 

        <!-- AdminLTE App -->
       
        <script src="@Url.Content("~/Scripts/AdminLTE/app.js")"></script>
        

        <script type="text/javascript">



            function get_Ajax_Data(url) {
                if (url != '')
                    $.ajax({
                        type: 'POST',
                        url: 'http://localhost:53887/' + url,
                        beforeSend: function () {
                            // setting a timeout
                            $('#preLoader').show();
                            $('#contentArea').html('');
                        },
                        success: function (data) {
                            $('#contentArea').html(data);
                            $('#preLoader').hide();
                        },
                        error: function (xhr) {
                            $('#preLoader').show();
                        }
                    });


                }



                $(window).on('hashchange', function (e) {
                    url = '';
                    var url = location.hash.replace(/^#/, '');
                    if (url.length < 1) {
                        url = '';
                    }

                    get_Ajax_Data(url);

                });


        </script>

    </head>



    <body class="skin-blue">
    

ERP/Views/shared/_sidebar_left.cshtml
<aside class=" sidebar-offcanvas">
                <!-- sidebar: style can be found in sidebar.less -->
                <section class="sidebar">
                    <!-- Sidebar user panel -->
                    <div class="user-panel">
                        <div class="pull-left image">
                            <img src='@Url.Content("~/Content/img/avatar3.png")' class="img-circle" alt="User Image" />
                        </div>
                        <div class="pull-left info">
                            <p>Hello, Jane</p>

                            <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                        </div>
                    </div>
                    <!-- search form -->
                    <form action="#" method="get" class="sidebar-form">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="Search..."/>
                            <span class="input-group-btn">
                                <button type='submit' name='seach' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i></button>
                            </span>
                        </div>
                    </form> 
                    <!-- /.search form -->
                    <!-- sidebar menu: : style can be found in sidebar.less -->
                    <ul class="sidebar-menu">
                        <li class="active">
                            <a href="~/home/index/">
                                <i class="fa fa-dashboard"></i> <span>System Board</span>
                            </a>
                        </li>
                        <li>
                            <a href="pages/widgets.html">
                                <i class="fa fa-th"></i> <span>Widgets</span> <small class="badge pull-right bg-green">new</small>
                            </a>
                        </li>

                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-bar-chart-o"></i>
                                <span>User Management</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="#user/"><i class="fa fa-angle-double-right"></i> User Create</a></li>
                                <li><a href="pages/charts/flot.html"><i class="fa fa-angle-double-right"></i> Role Create</a></li>
                                <li><a href="pages/charts/inline.html"><i class="fa fa-angle-double-right"></i> Assign Role</a></li>
                            </ul>
                        </li>



                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-bar-chart-o"></i>
                                <span>Charts</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/charts/morris.html"><i class="fa fa-angle-double-right"></i> Morris</a></li>
                                <li><a href="pages/charts/flot.html"><i class="fa fa-angle-double-right"></i> Flot</a></li>
                                <li><a href="pages/charts/inline.html"><i class="fa fa-angle-double-right"></i> Inline charts</a></li>
                            </ul>
                        </li>


                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-laptop"></i>
                                <span>UI Elements</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/UI/general.html"><i class="fa fa-angle-double-right"></i> General</a></li>
                                <li><a href="pages/UI/icons.html"><i class="fa fa-angle-double-right"></i> Icons</a></li>
                                <li><a href="pages/UI/buttons.html"><i class="fa fa-angle-double-right"></i> Buttons</a></li>
                                <li><a href="pages/UI/sliders.html"><i class="fa fa-angle-double-right"></i> Sliders</a></li>
                                <li><a href="pages/UI/timeline.html"><i class="fa fa-angle-double-right"></i> Timeline</a></li>
                            </ul>
                        </li>


                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-edit"></i> <span>Forms</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/forms/general.html"><i class="fa fa-angle-double-right"></i> General Elements</a></li>
                                <li><a href="pages/forms/advanced.html"><i class="fa fa-angle-double-right"></i> Advanced Elements</a></li>
                                <li><a href="pages/forms/editors.html"><i class="fa fa-angle-double-right"></i> Editors</a></li>
                            </ul>
                        </li>


                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-edit"></i> <span>User</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="~/user/index"><i class="fa fa-angle-double-right"></i> Create User</a></li>
                            </ul>
                        </li>


                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-table"></i> <span>Tables</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/tables/simple.html"><i class="fa fa-angle-double-right"></i> Simple tables</a></li>
                                <li><a href="pages/tables/data.html"><i class="fa fa-angle-double-right"></i> Data tables</a></li>
                            </ul>
                        </li>

                        <li>
                            <a href="pages/calendar.html">
                                <i class="fa fa-calendar"></i> <span>Calendar</span>
                                <small class="badge pull-right bg-red">3</small>
                            </a>
                        </li>

                        <li>
                            <a href="pages/mailbox.html">
                                <i class="fa fa-envelope"></i> <span>Mailbox</span>
                                <small class="badge pull-right bg-yellow">12</small>
                            </a>
                        </li>

                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-folder"></i> <span>Examples</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="pages/examples/invoice.html"><i class="fa fa-angle-double-right"></i> Invoice</a></li>
                                <li><a href="pages/examples/login.html"><i class="fa fa-angle-double-right"></i> Login</a></li>
                                <li><a href="pages/examples/register.html"><i class="fa fa-angle-double-right"></i> Register</a></li>
                                <li><a href="pages/examples/lockscreen.html"><i class="fa fa-angle-double-right"></i> Lockscreen</a></li>
                                <li><a href="pages/examples/404.html"><i class="fa fa-angle-double-right"></i> 404 Error</a></li>
                                <li><a href="pages/examples/500.html"><i class="fa fa-angle-double-right"></i> 500 Error</a></li>
                                <li><a href="pages/examples/blank.html"><i class="fa fa-angle-double-right"></i> Blank Page</a></li>
                            </ul>
                        </li>
                    </ul>
                </section>
                <!-- /.sidebar -->
            </aside>